server:
  port: 8080

spring:
  application:
    name: employee
  datasource:
    password: 'alex1999'
    url: jdbc:postgresql://localhost:5432/employee
    username: 'alex'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true